apiVersion: apps/v1 
kind: Deployment
metadata:
  name: httpd-deploy 
  labels:
    app: webserver
    type: html
spec:
  selector:
    matchLabels:
      type: html
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webserver
        type: html
    spec:
      containers:
      - image: httpd
        name: webserver
        ports:
        - containerPort: 80
          name: webserver
        volumeMounts:
        - name: webserver-pv
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: webserver-pv
        persistentVolumeClaim:
    
          claimName: pvc-html