apiVersion: apps/v1 
kind: Deployment
metadata:
  name: httpd-deployment 
  labels:
    app: webserver
    type: html
spec:
  selector:
    matchLabels:
      type: html
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webserver
        type: html
    spec:
      containers:
      - image: httpd
        name: webserver
        ports:
        - containerPort: 80
          name: httpd-service
